### ISSUE TITLE
Support prefix & suffix trigger filters in tmctl

### ISSUE THREAD

**Issue by jmcx** [triggermesh/tmctl#215]
Example: I'm using geographic and category information in my event types, like `us-groceries`, `eu-fashion`, `eu-books`. I'm routing different regions or categories to different targets. But I'd like to be able to say that all `eu`-related events should go to one place regardless of the category, and all `books`-related events should go to another place regardless of the region.

In the TriggerMesh Trigger CRD, AFAIK this is already supported (@odacremolbap to confirm) and would be done as: 

```
spec:
    filters:
        - prefix:
            type: eu
```

and

```
spec:
    filters:
        - suffix:
            type: books
```

How can we surface this in tmctl, in which the main filter param we have is `tmctl create trigger --eventTypes`.

We might also keep in mind that we plan to add content-based filtering in the near future. 

A couple solution ideas:

Go for a new rich filter param: `tmctl create trigger --filter "{"suffix": {"type": "books"}}"`
Add separate params: `tmctl create trigger --eventTypes type1,typ2 --prefix books --suffix foobar`
