### ISSUE TITLE
Ksvc dump to DO points to wrong registry 

### ISSUE THREAD

**Issue by tzununbekov** [triggermesh/tmctl#264]
Actual manifest:

```yaml
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  labels:
    triggermesh.io/context: foo
    triggermesh.io/role: target
  name: sockeye
spec:
  template:
    spec:
      containers:
      - env: []
        image: docker.io/n3wscott/sockeye:v0.7.0
        name: user-container
```

`tmctl dump --platform digitalocean` output:

```yaml
- image:
    registry: triggermesh
    registry_type: DOCKER_HUB
    repository: sockeye
    tag: v0.7.0
  instance_count: 1
  instance_size_slug: professional-xs
  internal_ports:
  - 8080
  name: sockeye
```
