### ISSUE TITLE
Create a redis backed broker in tmctl

### ISSUE THREAD

**Issue by sebgoa** [triggermesh/tmctl#87]
When we create a broker we should be able to create a redis backed broker.

The redis cluster could be:

1. running locally in docker
2. running remotely

It could be done either via a config file of the CLI or via parameters when we create a broker

```
tmctl create broker --help
TriggerMesh broker

Usage:
  tmctl create broker <name> [flags]

Flags:
  -h, --help   help for broker

Global Flags:
      --broker string    Default broker name
      --version string   TriggerMesh components version (default "v1.21.1")
```

when the broker is backed by redis, the `dump` should create an object that uses the new triggermesh broker

I am assigning to Pablo

**Comment by sebgoa** [comment]
Right now we can set parameters for the memory backed broker in `config.yaml`:

```
context: do
triggermesh:
    broker:
        image: gcr.io/triggermesh/memory-broker:latest
        memory:
            buffer-size: "100"
            produce-timeout: 1s
    version: v1.22.0
```

We should be able to have the same for the redis backed broker, something like:

```
context: do
triggermesh:
    broker:
        image: gcr.io/triggermesh/redis-broker:latest
       args:
            address:
            username:
            password:
            tls-enabled: (optional)
            skip-verify: (optional)
    version: v1.22.0
```

**Comment by odacremolbap** [comment]
Note: I will be changing very soon the time formats from `go durations` to [ISO8601 duration](https://en.wikipedia.org/wiki/ISO_8601#Durations).

**Comment by tzununbekov** [comment]
With #227 merged, CLI config supports a redis-based broker:

```yaml
context: bar
triggermesh:
    version: v1.23.0
    broker:
        version: v1.1.0
        redis:
            address: 127.0.0.1:6666
            username: foo
            password: bar
            skip-verify: true
            tls-enabled: true
```

Broker's `image` attribute is hidden in favor of the `version` tag to avoid situations when the image is pointing to the in-memory broker and start attributes are defined for redis, or wise-versa.
